version: '3.4'

services:
  accountsms.webapi:
    container_name: "AccountsMS.WebApi"
    image: ${DOCKER_REGISTRY-}accountsmswebapi
    build:
      context: .
      dockerfile: src/Microservices/AccountsMS/AccountsMS.WebApi/Dockerfile
  
  identityms.webapi:
    container_name: "IdentityMS.WebApi"
    image: ${DOCKER_REGISTRY-}identitymswebapi
    build:
      context: .
      dockerfile: src/Microservices/IdentityMS/IdentityMS.WebApi/Dockerfile   

  mssqldb:
    container_name: "MsSqlDB"
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    depends_on:
      - broker
      - zookeeper

  init-broker:
    image: confluentinc/cp-kafka:latest
    container_name: init
    depends_on:
      - broker
