version: '3.4'

services:
  accountsms.webapi:
    container_name: "AccountsMS.WebApi"
    image: ${DOCKER_REGISTRY-}accountsmswebapi
    build:
      context: .
      dockerfile: src/Microservices/AccountsMS/AccountsMS.WebApi/Dockerfile
